# Generated by Django 2.1.4 on 2019-03-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='author',
            new_name='authors',
        ),
    ]
