# Generated by Django 2.1.4 on 2019-03-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_auto_20190318_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='each_discussion',
            name='comment',
            field=models.TextField(default='_'),
        ),
    ]
