# Generated by Django 2.1.4 on 2019-03-31 21:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190320_1829'),
        ('discussion', '0004_auto_20190318_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commented', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(default='')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Developer')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.Discussion')),
            ],
        ),
        migrations.RemoveField(
            model_name='each_discussion',
            name='commenter',
        ),
        migrations.RemoveField(
            model_name='each_discussion',
            name='discussion',
        ),
        migrations.DeleteModel(
            name='Each_discussion',
        ),
    ]
