# Generated by Django 2.1.4 on 2019-03-31 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0005_auto_20190331_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
