# Generated by Django 2.1.4 on 2019-04-10 13:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0006_auto_20190331_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
