# Generated by Django 2.1.5 on 2019-01-09 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_auto_20190109_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Developer'),
        ),
    ]
