# Generated by Django 2.1.5 on 2019-03-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0005_solution_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='solution_notebook',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
