# Generated by Django 2.1.5 on 2019-03-07 16:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0006_solution_solution_notebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
