# Generated by Django 2.1.5 on 2019-03-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0008_solution_solution_notebook_htmlver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='solution_notebook',
            field=models.FileField(upload_to=''),
        ),
    ]
