# Generated by Django 2.1.4 on 2018-12-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_auto_20181223_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='data',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
