# Generated by Django 2.1.4 on 2018-12-23 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_auto_20181223_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='clinician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='users.Clinician'),
        ),
    ]
