# Generated by Django 2.1.5 on 2019-01-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_auto_20181223_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
