# Generated by Django 2.1.5 on 2019-01-08 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_auto_20190108_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
