# Generated by Django 2.1.5 on 2019-01-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_challenge_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='date_posted',
            new_name='date_created',
        ),
    ]
