# Generated by Django 2.1.5 on 2019-01-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_auto_20190108_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='award',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
