# Generated by Django 2.1.5 on 2019-01-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_challenge_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='award',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Award in GBP'),
        ),
    ]
