# Generated by Django 2.1.5 on 2019-03-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_auto_20190129_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='evaluation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='challenge',
            name='rule',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='challenge',
            name='timeline',
            field=models.TextField(default=''),
        ),
    ]
