# Generated by Django 2.1.5 on 2019-03-05 19:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_auto_20190305_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
