# Generated by Django 2.1.5 on 2019-03-06 17:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0013_auto_20190305_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='evaluation',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='rule',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='timeline',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
