# Generated by Django 2.1.5 on 2019-03-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0014_auto_20190306_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='brief',
            field=models.CharField(default='', max_length=200),
        ),
    ]
