# Generated by Django 2.1.5 on 2019-03-07 12:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0015_challenge_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='award',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
