# Generated by Django 2.1.7 on 2019-04-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0018_auto_20190416_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='award',
            field=models.IntegerField(blank=True, default=0, max_length=10, verbose_name='Award in GBP'),
        ),
    ]
