# Generated by Django 2.1.7 on 2019-04-16 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0020_auto_20190416_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='award',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(1000000000)], verbose_name='Target cost saving in GBP'),
        ),
    ]
